# Generated by Django 5.1.7 on 2025-03-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_estudiante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nivel',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], default='primaria', max_length=10),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='seccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
